# Generated by Django 3.2.25 on 2024-07-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compfest', '0003_auto_20240702_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
