# Generated by Django 3.2.25 on 2024-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('compfest', '0004_remove_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='DefaultFirstName', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, default='default-id', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='DefaultLastName', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='08123456789', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(default='DefaultFirstName', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_name',
            field=models.CharField(default='DefaultLastName', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('haircuts_styling', 'Haircut and Styling'), ('manicure_pedicure', 'Manicure and Pedicure'), ('facial', 'Facial Treatment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='08123456789', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
